// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:d0895e4e-0c4d-45c0-a4eb-681ef76c97a7',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'tinyanthems-hosting-mobilehub-1742520150',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd196v3voat23t4.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a7974dfe8ec345b0aa14bba16107c6f2',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '319f86c6-20ce-11e8-b21f-6da413101de0',
    'aws_project_name': 'tiny-anthems-2018-03-05-15-37-27',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'tinyanthems-mobilehub-1742520150',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'tinyanthems-userfiles-mobilehub-1742520150',
    'aws_user_files_s3_bucket_region': 'us-west-1',
}

export default awsmobile;
